# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-25 16:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='photos/')),
                ('sitename', models.CharField(max_length=40)),
                ('url', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=6000)),
                ('category', models.CharField(max_length=6000)),
                ('tags', models.CharField(max_length=6000)),
                ('technology', models.CharField(max_length=6000)),
                ('designer', models.CharField(max_length=6000)),
                ('author', models.CharField(max_length=6000)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
