# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-27 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_voting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='category',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='designer',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='tags',
        ),
        migrations.AddField(
            model_name='foto',
            name='profiles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Profile'),
        ),
    ]
